config/routes.rb
Kiroku::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :records

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout',:to => 'sessions#destroy'

  match '/feed', :to => 'pages#feed'
  match '/contact', :to => 'pages#contact'

  root :to => 'pages#home'

end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :title, :content, :tag_names
  attr_writer :tag_names

  belongs_to :user
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings

  validates :title,   :length => { :maximum => 100 }

  validates :content, :presence => true,
                      :length => { :maximum => 10.kilobytes }

  before_save :count_words
  after_save :assign_tags
  default_scope :order => 'records.created_at DESC'
  scope :published #stub TODO : implement publish function

  def tag_names
    @tag_names ||= tags.map{ |tag| tag.name }.join( ', ')
  end

  private
    def count_words
      self.word_count = content.split.size
    end

    def assign_tags
      if @tag_names
        self.tags = @tag_names.split( /\s*[,;]\s*/ ).map do |name|
          Tag.find_or_create_by_name( name )
        end
      end
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  has_many :records, :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :record
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  # introduced in Rails 3.1, needs gem bcrypt-ruby, needs password_digest column,
  # provides password and password_confirmation
  has_secure_password
  has_many :records, :dependent => :destroy

  email_regex = /\A[a-z\d][\w+\-.]*@[a-z\d\-.]+\.[a-z]{2,4}\z/i

  validates :name,      :presence => true,
                        :length   => { :maximum => 50 }

  validates :email,     :presence => true,
                        :format   => { :with => email_regex } 

  validates :password,  :length   => { :within => 6..40 }

  default_scope :order => "users.created_at DESC"

  def salt
    BCrypt::Password.new(password_digest).salt
  end

  def self.authenticate(email, password)
    User.find_by_email(email).try( :authenticate, password )
  end

  def self.authenticate_with_token(id, salt)
    user = User.find_by_id(id) #doesn't raise exception if id is nil
    return user if user && salt == user.salt
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.authenticate_with_token(*remember_token)
  end
  helper_method :current_user

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to new_record_path if signed_in?
    @title = "Home"
    @records = Record.published.paginate( :page => 1, :per_page => 5 )
  end

  def contact
    @title = "Contact"
  end

  def feed
    @title = "Feed"
    @records = Record.paginate(:page => params[:page], :per_page =>20)
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_filter :authenticate
  before_filter :check_user, :only => [:update, :edit, :destroy]


  def index
    @records = current_user.records.paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @record = Record.new 
  end

  def create
    @record = current_user.records.build(params[:record])
    if @record.save
      redirect_to @record
    else
      render 'new'
    end
  end

  def show
    @record = Record.find(params[:id])
    @user = @record.user
  end
  
  def edit
    @record = Record.find(params[:id])
    @user = @record.user
  end

  def update
    @record = Record.find(params[:id])
    if @record.update_attributes(params[:record])
      redirect_to @record
    else
      render 'edit'
    end
  end

  def destroy
    Record.find(params[:id]).destroy
    redirect_to records_path
  end

  protected
  
  def check_user
    @user = Record.find_by_id(params[:id]).user
    redirect_to root_path unless current_user?(@user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @title = 'Sign in'
    #@debug_info = { :cookies => cookies }
  end

  def create
    if user = User.authenticate(params[:session][:email], 
                                params[:session][:password]) 
      sign_in user
      #flash[:success] = "Welcome, #{user.name}!"
      redirect_back_or root_path
    else
      @title = 'Sign in'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate, :only => [:index, :show, :edit, :update]
before_filter :check_user, :only => [:edit, :update]
before_filter :check_admin, :only => :destroy
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @records = @user.records.paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @title = "Sign up"
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @title = "Edit profile"
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      @title = "Edit profile"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end
  
  protected

  def check_user
    @user = User.find_by_id(params[:id])
    redirect_to root_path unless current_user?(@user) 
  end

  def check_admin
    redirect_to root_path unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis
  def title
    base_title = "Kiroku"
    return base_title + " | " + @title unless @title.nil?
    base_title
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/records_helper.rb
module RecordsHelper

  def record_start_time(record)
    t = record.created_at
    Time.now - t < 7.day ? time_ago_in_words(t) + " ago" : "on " + t.strftime( "%b %d, %Y")
  end
 
  def record_owner_display(record)
     unless [params[:action], params[:controller]] == ["index", "records"]
      user_name = current_user?(record.user) ? "You" : record.user.name.capitalize
      ("by " + link_to(user_name, user_path(record.user)) )
      .html_safe
     end
  end

  def record_content_head(record)
    content = h(record.content)
    # first take the 10 first lines, delete the blank lines, 
    # wrap it, then take the 3 first resulting lines
    content_preview = word_wrap( content.match( /(?:.*\n){0,10}[^\n]*/ )[0].gsub( /[\r\n]+/, "\n"),
                                 :line_width => 80 
                                 ).match( /(?:.*\n){0,2}[^\n]*/ )[0]
    if (content_preview.length + 10 <= content.length) && record.word_count
        content_preview += " ... " \
                  + '<span class="stats">(' + record.word_count + ' words)</span>' 
    end
    simple_format(content_preview ) 
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in( user )
    cookies.permanent.signed[:remember_me] = [ user.id, user.salt ]
    self.current_user = user
  end
    
  def sign_out
    cookies.delete(:remember_me)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def remember_token
   cookies.signed[:remember_me] || [nil, nil] 
  end

  # friendly redirection

  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please log in to perform this action"
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def clear_return_to
    session[:return_to] = nil
  end
 
  def authenticate
    deny_access unless signed_in?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>

app/views/layouts/_header.html.erb
<header>
  <div id="banner">
    <div id="banner-left" class="centered" >
     <%= link_to root_path do %>
       <h1>Ki<red>|r|</red>oku</h1>
     <% end %>
     <small>record your thoughts</small>
    </div>
    <div id="banner-right" class="centered" >
    <% if signed_in? %>
      Welcome, <%= link_to current_user.name.capitalize, current_user %>
    <% end %>
      <div class="banner-links">
        <% if signed_in? %><%= link_to "Sign out", signout_path %>
        <% else %><%= link_to "Sign in", signin_path %><% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <div>
      <li><%= link_to "New Record", new_record_path %></li>
      <li><%= link_to "My Records", records_path %></li>
     </div>
    <div>
      <li><%= link_to "Users Publishings", feed_path %></li>
    </div>
    <div>
      <li><%= link_to "Users", users_path %></li>
    </div>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <table>
      <tr>
      <% if signed_in? %>
        <td width="150" valign="top" class="nav">
          <%= render 'layouts/navigation', :flash => flash %>
        </td>
      <% end %>
        <td valign="top" class="container">
        <%= render 'layouts/flash', :flash => flash %>
            <%= yield %>
        </td>
      </tr>
    </table>
    <%= debug( @debug_info ) if @debug_info && Rails.env.development? %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/feed.html.erb
<h1>Users Publishing Feed</h1>
<h3>recently published by users:</h3>
<div class="records-feed">
  <%= render @records %>
  <%= will_paginate @records %>
</div>

app/views/pages/home.html.erb
<h1>Ki(r)oku Home</h1>
<div>
  <div class="kiroku-description">
    <p>
      <strong>Kiroku</strong> is a platform for uploading, and managing one's thoughts, <br/>
      or <strong>records</strong>, with the possibility of <strong>publishing</strong> them in the form of <br/>
      articles.
    </p>
    <p>Not a user yet? <%= link_to "Create an accout", signup_path %></p>
  </div>
  <div class="mini-feed">
  <h2>Recent activities:</h2>
    <%= render @records %>
  </div>
</div>

app/views/records/_action_buttons.html.erb
<div class="action-buttons">
  <% if signed_in? %>
    <%= button_to "View", record, :method => 'get', :class => "view-button" %>
    <% if [params[:controller], params[:action]] == [ "records", "index"] %>
      <%= button_to "Edit", edit_record_path(record), :method => 'get', :class => "edit-button" %>
      <%= button_to "Delete", record, :method => 'delete', 
                                      :confirm => "are you sure?",
                                      :class => "delete-button" %>
    <% end %>
  <% end %>
</div>

app/views/records/_record.html.erb
    <div class="record-item">
        <div class="record-title">
          <%= record.title %>
        </div>
        <div class="record-info">
          Started <%= record_start_time(record) %>
            <%= record_owner_display(record) %>
        </div>
        <div class="record-tags">
          <%= record.tag_names %>
         </div>
        <div class="record-tags"><% "#TODO" %></div>
        <div class="record-head">
          <%= record_content_head(record) %>
        </div>
      <%= render 'records/action_buttons', :record => record %>
    </div>
    

app/views/records/_record_form.html.erb
<div class="record-form">
  <%= form_for @record do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
    <%= f.label :content, "Please start writing !" %>
  <div>
    <%= f.text_area :content, :rows => 20, :cols => 80 %>
  </div>
  <div>
    <%= f.label :tag_names, "Tag names" %>
    <%= f.text_field :tag_names %>
  </div>
  <div>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
    <%= f.submit "Record" %>
  </div>
  <% end %>
</div>

app/views/records/edit.html.erb
<h1>Edit Record</h1>
  <%= render 'record_form' %>

app/views/records/index.html.erb
<h1>Your records</h1>
<% if @records.empty? %>
  You haven't written any record yet... <%= link_to "Start writing now!", new_record_path %>
<% else %>
  <%= render @records %> 
<% end %>

app/views/records/new.html.erb
<h1>New record</h1>
  <%= render 'record_form' %>

app/views/records/show.html.erb
<div class="record-show">
  <div class="record-title">
    <%= @record.title %>
  </div>
  <div class="record-info">
     Started <%= record_start_time(@record) %>
     <%= record_owner_display(@record) %>
  </div>
  <div class="record-tags">
    <%= @record.tags.map(&:name).join( ', ') %>
   </div>
  <div class="record-content">
    <%= simple_format word_wrap(@record.content, :line_width => 100) %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <%= @title %> failed due to the following problems:
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_record_form.html.erb
<div class="record-form">
  <%= form_for @record do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
    <%= f.label :content, "Please start writing !" %>
  <div>
    <%= f.text_area :content, :rows => 20, :cols => 80 %>
  </div>
  <div>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title %>
    <%= f.submit "Record" %>
  </div>
  <% end %>
</div>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <p><%= @title %> failed due to the following problems:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_fields.html.erb
  <%= render 'shared/error_messages', :object => f.object %>
  <div>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, "Confirmation" %><br/>
    <%= f.password_field :password_confirmation %>
  </div>

app/views/users/_user.html.erb
    <tr>
      <td><%= link_to user.name, user %></td>
      <td>suscribed <%= time_ago_in_words(user.created_at) %> ago</td>
      <% if current_user.admin? %>
      <td><%= link_to "delete", user, :method => :delete, 
                                :confirm => "are you sure?", 
                                :title => "Delete #{user.name}" %></td>
      <% end %>
    </tr>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div>
    <%= f.submit "Update profile" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<%= will_paginate %>
<div>
  <table>
  <%= render @users %>
  </table>
</div>
<%= will_paginate %>

app/views/users/new.html.erb
<div id="login-area">
  <h1>Sign up</h1>

  <p>Please fill in following informations:</p>
  <div class="form-box">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="submit">
        <%= f.submit "Sign'up" %>
      </div>
    <% end %>
  </div>
 </div>
<div id="papyrus">
  <%= image_tag "papyrus_transparent50.png", :height => "200" %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= @user.email %>
<% if current_user?(@user) %>
  <p>Edit profile <%= link_to "settings", edit_user_path %></p>
<% end %>
<% unless @records.published.empty? %>
  <h2>recently published:</h2>
  <div class="records-feed">
    <%= render @records %> 
    <%= will_paginate @records %>
  </div>
<% end %>